CREATE TABLE category (
    id SERIAL PRIMARY KEY ,
    name VARCHAR(20) NOT NULL UNIQUE,
    description TEXT NOT NULL,
    user_id INTEGER NOT NULL REFERENCES "user"(id) ON DELETE CASCADE, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);